### ISSUE TITLE
003 AddTwoNumbers 입력부분 어떻게 하시는지요?

### ISSUE THREAD

**Issue by ghost** [iamprogrammer-study/codinginterview#11]
문제 정의에서는 입력을 받고 연산 후 출력을 하는 것으로 보입니다.
1) 입력을 받아 리스트로 저장한다.
2) 덧셈연산
3) 형식에 맞게 출력한다.

표준입력 받아서 파싱해서 리스트로 만든다거나 그런 과정은 생략해도 되는지요?

**Comment by hunj** [comment]
출처를 확인하시면 `ListNode` 가 어떤 구조로 되어있는지 나와있는데요, 함수에 들어가는 입력(parameters)은 `l1` , `l2` 로 두개의 `ListNode` 이며, 반환(return)해야 하는 건 리스트입니다.

**Comment by ghost** [comment]
@hunj 
오 그렇네요. 제가 오버를 했군요. 
딱 그 부분만 구현하면 되겠습니다. 감사합니다^^
